; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

	TITLE	J:\for_linux_file\work\3D-Builder\3D-Builder\Release\rcc\qrc_Builder.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?qInitResources_Builder@@YAHXZ			; qInitResources_Builder
PUBLIC	?qCleanupResources_Builder@@YAHXZ		; qCleanupResources_Builder
EXTRN	_atexit:PROC
_BSS	SEGMENT
?dummy@?A0x1cae75a1@@3Uinitializer@1@A DB 01H DUP (?)	; `anonymous namespace'::dummy
_BSS	ENDS
CRT$XCU	SEGMENT
?dummy$initializer$@?A0x1cae75a1@@3P6AXXZA DD FLAT:??__Edummy@?A0x1cae75a1@@YAXXZ ; `anonymous namespace'::dummy$initializer$
CRT$XCU	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Fdummy@?A0x1cae75a1@@YAXXZ
text$yd	SEGMENT
??__Fdummy@?A0x1cae75a1@@YAXXZ PROC			; `anonymous namespace'::`dynamic atexit destructor for 'dummy'', COMDAT
	ret	0
??__Fdummy@?A0x1cae75a1@@YAXXZ ENDP			; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
text$yd	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Edummy@?A0x1cae75a1@@YAXXZ
text$di	SEGMENT
??__Edummy@?A0x1cae75a1@@YAXXZ PROC			; `anonymous namespace'::`dynamic initializer for 'dummy'', COMDAT
; File J:\for_linux_file\work\3D-Builder\3D-Builder\Release\rcc\qrc_Builder.cpp
; Line 45
	push	OFFSET ??__Fdummy@?A0x1cae75a1@@YAXXZ	; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
	call	_atexit
	pop	ecx
	ret	0
??__Edummy@?A0x1cae75a1@@YAXXZ ENDP			; `anonymous namespace'::`dynamic initializer for 'dummy''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qCleanupResources_Builder@@YAHXZ
_TEXT	SEGMENT
?qCleanupResources_Builder@@YAHXZ PROC			; qCleanupResources_Builder, COMDAT
; File J:\for_linux_file\work\3D-Builder\3D-Builder\Release\rcc\qrc_Builder.cpp
; Line 38
	mov	eax, 1
; Line 39
	ret	0
?qCleanupResources_Builder@@YAHXZ ENDP			; qCleanupResources_Builder
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qInitResources_Builder@@YAHXZ
_TEXT	SEGMENT
?qInitResources_Builder@@YAHXZ PROC			; qInitResources_Builder, COMDAT
; File J:\for_linux_file\work\3D-Builder\3D-Builder\Release\rcc\qrc_Builder.cpp
; Line 32
	mov	eax, 1
; Line 33
	ret	0
?qInitResources_Builder@@YAHXZ ENDP			; qInitResources_Builder
_TEXT	ENDS
END
